
version: '3.3'

services:
#wordpress
  wordpress:
    image: wordpress
    restart: always

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: azertysio
      WORDPRESS_DB_NAME: wordpress

    ports:
      - 8080:80
    depends_on:
      - db

#mariadb

  db:
    image: mariadb
    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: azertysio
      MARIADB_DATABASE: test
      MARIADB_USER: paugetc
      MARIADB_PASSWORD: azertysio

    ports:
      - 3308:3306
    

#phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    
    environment:
      PMA_HOST: db
      #PMA_USER: sio
      #PMA_PASWORD: azertysio

    ports:
      - 8081:80

    depends_on:
      - db